# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Person'),
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='Backend.Person'),
        ),
    ]
