# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong', to='Backend.Person'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='Backend.Person'),
        ),
    ]
