# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20190310_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='photo_url',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='myBooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_books', to='Backend.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='readingBooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='reading_books', to='Backend.Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong', to='Backend.Person'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_books', to='Backend.Book'),
        ),
        migrations.AddField(
            model_name='company',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_books', to='Backend.Book'),
        ),
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_workers', to='Backend.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_author', to='Backend.Person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_book', to='Backend.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_book', to='Backend.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library', to='Backend.Company'),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(related_name='company_workers', to='Backend.Company'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_books', to='Backend.Genre'),
        ),
    ]
