# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
    ]
