# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 14, 4, 25, 864892, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
