# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20190315_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AlterField(
            model_name='message',
            name='sended_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 6, 44, 34, 854154, tzinfo=utc)),
        ),
    ]
