# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20190316_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 8, 43, 56, 987823, tzinfo=utc)),
        ),
    ]
