# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_auto_20190316_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
