# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_auto_20190316_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='person',
            name='myBooks',
        ),
        migrations.RemoveField(
            model_name='person',
            name='readingBooks',
        ),
        migrations.AddField(
            model_name='book',
            name='company_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='read',
            field=models.ManyToManyField(blank=True, to='Backend.Book'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
