# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_auto_20190316_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
