# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_book_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='Backend.Person'),
        ),
    ]
