# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_book_requesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Book')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.Person')),
            ],
        ),
    ]
