# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
