# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_auto_20190316_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='book',
        ),
        migrations.RemoveField(
            model_name='community',
            name='person',
        ),
        migrations.AddField(
            model_name='community',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_person', to='Backend.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='bo0k',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_book', to='Backend.Book'),
            preserve_default=False,
        ),
    ]
