# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_auto_20190317_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='bo0k',
            new_name='book',
        ),
    ]
