# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_auto_20190317_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_book', to='Backend.Book'),
            preserve_default=False,
        ),
    ]
